clients/urls.py
from django.conf.urls.defaults import *
 
urlpatterns = patterns('clients.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<slug>[\w-]+)/$', 'detail', name='detail'),
)

export/urls.py
from django.conf.urls.defaults import *
 
urlpatterns = patterns('export.views',
    url(r'^$', 'index', name='home'),
    url(r'^login/$', 'home_login', name='login'),
)

exportrecord/urls.py
from django.conf.urls.defaults import include, patterns, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^', include('export.urls', namespace='export'), name='records'),
    url(r'^clients/', include('clients.urls', namespace='clients'), name='clients'),
    url(r'^suppliers/', include('suppliers.urls', namespace='suppliers'), name='suppliers'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suppliers/urls.py
from django.conf.urls.defaults import *
 
urlpatterns = patterns('suppliers.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<slug>[\w-]+)/$', 'detail', name='detail'),
)

clients/models.py
from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(help_text='The slug is filled automatically from the name')

    def __unicode__(self):
        return u'%s' % self.name

export/models.py
import locale
import os

from django.db import models

from clients.models import Client
from suppliers.models import Supplier
from utils.amount import decimal_separator

locale.setlocale(locale.LC_ALL, '')


class Country(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Currency(models.Model):
    code = models.CharField(max_length=5)
    country = models.ForeignKey(Country)

    class Meta:
        ordering = ['code']

    def __unicode__(self):
        return self.code


class Buyer(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name


class Container(models.Model):
    CONTAINER_CHOICES = (
        ('20', '20 ft'),
        ('40', '40 ft'),
        ('40HC', '40 ft High Cube'),
        ('LCL', 'LCL'),
    )

    type = models.CharField(max_length=4, choices=CONTAINER_CHOICES)
    quantity = models.IntegerField()

    class Meta:
        ordering = ['type', 'quantity']

    def __unicode__(self):
        return u'%ix%s' % (self.quantity, self.type)


class Forwarder(models.Model):
    name = models.CharField(max_length=40)

    def __unicode__(self):
        return self.name


class Record(models.Model):

    PAYMENT_CHOICES = (
        ('LS', 'L/C ST'),
        ('L30', 'L/C 30'),
        ('L60', 'L/C 60'),
        ('L90', 'L/C 90'),
        ('L120', 'L/C 120'),
        ('TT', 'TT'),
    )

    date = models.DateField()
    file_no = models.CharField(max_length=100)
    supplier = models.ForeignKey(Supplier, null=True)
    proforma_invoice = models.CharField(max_length=100)  # proforma invoice number
    container = models.ManyToManyField(Container)
    order_confirm = models.CharField(max_length=100, blank=True)
    payment_term = models.CharField(max_length=4, choices=PAYMENT_CHOICES, verbose_name='P.Term')
    currency = models.ForeignKey(Currency, verbose_name='CURR')
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    country = models.ForeignKey(Country)
    shipment_date = models.DateField(null=True, blank=True)
    buyer = models.ForeignKey(Buyer)
    forwarder = models.ForeignKey(Forwarder, null=True, blank=True)
    client = models.ForeignKey(Client)
    note = models.TextField(blank=True)
    payment_status = models.BooleanField(default=False)

    class Meta:
        ordering = ['file_no']

    def __unicode__(self):
        return u'%s - %s' % (self.date, self.supplier)

    def amount_format(self):
        return decimal_separator(self.amount)
    amount_format.short_description = 'Amount'

    def container_quantity(self):
        return self.container.all()
    container_quantity.short_description = 'TC.Qty'

def invoice_file_name(instance, filename):
    ''' Upload file to under a folder with the record id '''
    return os.path.join('proforma_invoice', str(instance.record_id), filename)

class ProformaInvoiceFile(models.Model):
    file = models.FileField(upload_to=invoice_file_name, null=True, blank=True)
    record = models.ForeignKey(Record)

    def __unicode__(self):
        if self.file:
            return os.path.basename(self.file.path)
        else:
            return 'nothing'

suppliers/models.py
from django.db import models

from utils.amount import decimal_separator

class Supplier(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(help_text='The slug is filled automatically from the name')

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return u'%s' % self.name

    def total(self):
        records = self.record_set.all()
        currency = ''
        total_amount = 0

        for record in records:
            currency = record.currency
            total_amount += record.amount
        #return '%s %s' % (currency, decimal_separator(total_amount))
        return {
            'currency': currency, 
            'amount': decimal_separator(total_amount)
        }

clients/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def index(request):
    data = {
    }

    return render_to_response(
        'clients/index.html',
        data,
        context_instance=RequestContext(request)
    )   

export/views.py
from django.contrib.auth import authenticate, login
from django.db.models import Q
from django.shortcuts import redirect, render
from django.template import RequestContext

from export.models import Record
 
def index(request):
    q = ''
    if 'q' in request.GET:
        q = request.GET['q']

    records = Record.objects.filter(
        Q(buyer__name__icontains=q) |
        Q(order_confirm__icontains=q) |
        Q(proforma_invoice__icontains=q) |
        Q(supplier__name__icontains=q)
    ).order_by('file_no')

    data = { 
        'records': records
    }   

    return render(
        request,
        'export/index.html',
        data,
    )   
 
def home_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('export:home')
            else:
                # Return a 'disabled account' error message
                print 'disabled account'
        else:
            # Return an 'invalid login' error message.
            print 'invalid account'

    return render(
        request,
        'export/login.html',
        {},
    )   

suppliers/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext

from suppliers.models import Supplier

def index(request):
    suppliers = Supplier.objects.order_by('name')

    data = {
        'suppliers': suppliers
    }

    return render_to_response(
        'suppliers/index.html',
        data,
        context_instance=RequestContext(request)
    )

def detail(request, slug):
    supplier = get_object_or_404(Supplier, slug=slug)
    records = supplier.record_set.order_by('file_no')
    total = supplier.total()

    data = {
        'records': records,
        'supplier': supplier,
        'total': total
    }

    return render_to_response(
        'suppliers/detail.html',
        data,
        context_instance=RequestContext(request)
    )

utils/views.py
# Create your views here.

exportrecord/templates/base.html
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"> 
    <title>Export Records</title> 
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/base.css" media="screen" />
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/results.css" media="screen" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script> 
    <script type="text/javascript" src="{{ STATIC_URL }}js/export_record.js"></script> 
  </head>
  <body>
  <div id="header">
    <h2><a href="{% url export:home %}">Export Records - {% block page-header %}Results{% endblock %}</a></h2>
    <div id="top-navigation">
      <a href="{% url export:home %}">Results</a>
      <a href="{% url clients:index %}">Clients</a>
      <a href="{% url suppliers:index %}">Suppliers</a>
    </div>
  </div>
  <div id="content">
    {% block content %}{% endblock %}
  </div>
  <div id="footer">
  </div>
  </body>
</html>

exportrecord/templates/clients/detail.html
{% extends "base.html" %}

{% block page-header %}
Clients
{% endblock %}

{% block content %}
{% include "export/results.html" %}

{% endblock %}

exportrecord/templates/clients/index.html
{% extends "base.html" %}

{% block page-header %}
Clients
{% endblock %}

{% block content %}
<h3>Clients</h3>
<ol>
{% for client in clients %}
  <li><a href="{% url clients:detail client.slug %}">{{ client }}</a></li>
{% endfor %}
</ol>
{% endblock %}

exportrecord/templates/export/index.html
{% extends "base.html" %}

{% block content %}

<form action="/" method="get">
  <input type="text" name="q" />
  <input type="submit" value="Search" />
  <a href="" id="display-columns">Display Columns</a>
  <div id="select-columns">
    <h4>Select columns to display</h4>
    <input type="checkbox" name="amount" class="column-display" />Amount<br />
    <input type="checkbox" name="buyer" class="column-display" />Buyer<br />
    <input type="checkbox" name="supplier" class="column-display" />Supplier<br />
  </div>
</form>

{% include "export/results.html" %}

{% endblock %}

exportrecord/templates/export/login.html
<h2>Login Page</h2>
 
<form actions="{% url export:login %}" method="post" id="login-form">{% csrf_token %}
  <label for="id_username">Username:</label> <input type="text" name="username" id="id_username" />
  <label for="id_password">Password:</label> <input type="password" name="password" id="id_password" />
  <input type="submit" />
</form>

exportrecord/templates/export/results.html
{% if records %}
  <table>
    <tr>
      <th class="date">Date</th>
      <th>File no</th>
      <th class="buyer">Buyer</th>
      <th class="supplier">Supplier</th>
      <th>Proforma Invoice</th>
      <th>TC.Qty</th>
      <th>Order Confirm</th>
      <th>P.Term</th>
      <th>CURR</th>
      <th class="amount">Amount</th>
      <th>Country</th>
      <th class="shipment-date">Shipment Date</th>
      <th>Forwarder</th>
      <th class="note">Note</th>
      <th>Payment Status</th>
    </tr>
  {% for record in records %}
    <tr>
      <td class="date"><a href="{% url admin:export_record_changelist %}{{ record.id }}">{{ record.date }}</a></td>
      <td>{{ record.file_no }}</td>
      <td class="buyer">{{ record.buyer }}</td>
      <td class="supplier">{{ record.supplier }}</td>
      <td>
      {% if record.proformainvoicefile_set.all %}
        <b>{{ record.proforma_invoice }}:</b>
        {% for f in record.proformainvoicefile_set.all %}
          <a href="{{ MEDIA_URL }}{{ f.file }}">{{ f }}</a>
        {% endfor %}
      {% else %}
        {{ record.proforma_invoice }}
      {% endif %}
      </td>
      <td>
        <ul id="containers">
        {% for container in record.container.all %}
          <li>{{ container }}</li>
        {% endfor %}
        </ul>
      </td>
      <td>{{ record.order_confirm }}</td>
      <td>{{ record.payment_term }}</td>
      <td>{{ record.currency }}</td>
      <td class="amount">{{ record.amount_format }}</td>
      <td>{{ record.country }}</td>
      <td class="shipment-date">{{ record.shipment_date }}</td>
      <td>{{ record.forwarder }}</td>
      <td class="note">{{ record.note }}</td>
      <td>
      {% if record.payment_status %}
        <img src="{{ STATIC_URL }}admin/img/icon-yes.gif" />
      {% else %}
        <img src="{{ STATIC_URL }}admin/img/icon-no.gif" />
      {% endif %}
      </td>
    </tr>
  {% endfor %}
  {% if total %}
    <tr class="total-row">
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td class="total">Total:</td>
      <td class="total">{{ supplier.total.currency }}</td>
      <td class="total">{{ supplier.total.amount }}</td>
    </tr>
  {% endif %}
  </table>
{% else %}
  <h4>No results found</h4>
{% endif %}

exportrecord/templates/suppliers/detail.html
{% extends "base.html" %}

{% block page-header %}
Suppliers
{% endblock %}

{% block content %}
<h2>{{ supplier }}</h2>

{% include "export/results.html" %}

{% endblock %}

exportrecord/templates/suppliers/index.html
{% extends "base.html" %}

{% block page-header %}
Suppliers
{% endblock %}

{% block content %}
<h3>Suppliers</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Total</th>
  </tr>
{% for supplier in suppliers %}
  <tr>
    <td><a href="{% url suppliers:detail supplier.slug %}">{{ supplier }}</a></td>
    <td>{{ supplier.record_set.currency }}{{ supplier.total.currency }} {{ supplier.total.amount }}</td>
  </tr>
{% endfor %}
</table>
{% endblock %}

templates/base.html
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"> 
    <title>Export Records</title> 
    <link type="text/css" rel="stylesheet" href="{{ MEDIA_URL }}css/base.css" media="screen" />
    <link type="text/css" rel="stylesheet" href="{{ MEDIA_URL }}css/results.css" media="screen" />
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.js"></script> 
    <script type="text/javascript" src="{{ MEDIA_URL }}js/export_record.js"></script> 
  </head>
  <body>
  <div id="header">
    <h2><a href="{% url export:home %}">Export Records - {% block page-header %}Results{% endblock %}</a></h2>
    <div id="top-navigation">
      <a href="{% url export:home %}">Results</a>
      <a href="{% url clients:index %}">Clients</a>
      <a href="{% url suppliers:index %}">Suppliers</a>
    </div>
  </div>
  <div id="content">
    {% block content %}{% endblock %}
  </div>
  <div id="footer">
  </div>
  </body>
</html>

templates/export/login.html
<h2>Login Page</h2>
 
<form actions="{% url export:login %}" method="post" id="login-form">
  <label for="id_username">Username:</label> <input type="text" name="username" id="id_username" />
  <label for="id_password">Password:</label> <input type="password" name="password" id="id_password" />
  <input type="submit" />
</form>

templates/export/results.html
{% if records %}
  <table>
    <tr>
      <th class="date">Date</th>
      <th>File no</th>
      <th class="buyer">Buyer</th>
      <th class="supplier">Supplier</th>
      <th>Proforma Invoice</th>
      <th>TC.Qty</th>
      <th>Order Confirm</th>
      <th>P.Term</th>
      <th>CURR</th>
      <th class="amount">Amount</th>
      <th>Country</th>
      <th class="shipment-date">Shipment Date</th>
      <th>Forwarder</th>
      <th class="note">Note</th>
      <th>Payment Status</th>
    </tr>
  {% for record in records %}
    <tr>
      <td class="date"><a href="{% url admin:export_record_changelist %}{{ record.id }}">{{ record.date }}</a></td>
      <td>{{ record.file_no }}</td>
      <td class="buyer">{{ record.buyer }}</td>
      <td class="supplier">{{ record.supplier }}</td>
      <td>
      {% if record.proformainvoicefile_set.all %}
        <b>{{ record.proforma_invoice }}:</b>
        {% for f in record.proformainvoicefile_set.all %}
          <a href="{{ MEDIA_URL }}{{ f.file }}">{{ f }}</a>
        {% endfor %}
      {% else %}
        {{ record.proforma_invoice }}
      {% endif %}
      </td>
      <td>
        <ul id="containers">
        {% for container in record.container.all %}
          <li>{{ container }}</li>
        {% endfor %}
        </ul>
      </td>
      <td>{{ record.order_confirm }}</td>
      <td>{{ record.payment_term }}</td>
      <td>{{ record.currency }}</td>
      <td class="amount">{{ record.amount_format }}</td>
      <td>{{ record.country }}</td>
      <td class="shipment-date">{{ record.shipment_date }}</td>
      <td>{{ record.forwarder }}</td>
      <td class="note">{{ record.note }}</td>
      <td>
      {% if record.payment_status %}
        <img src="{{ ADMIN_MEDIA_PREFIX }}img/admin/icon-yes.gif" />
      {% else %}
        <img src="{{ ADMIN_MEDIA_PREFIX }}img/admin/icon-no.gif" />
      {% endif %}
      </td>
    </tr>
  {% endfor %}
  {% if total %}
    <tr class="total-row">
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td class="total">Total:</td>
      <td class="total">{{ supplier.total.currency }}</td>
      <td class="total">{{ supplier.total.amount }}</td>
    </tr>
  {% endif %}
  </table>
{% else %}
  <h4>No results found</h4>
{% endif %}